import abjad

metadata = abjad.OrderedDict(
    [
        (
            "bol_measure_numbers",
            [556, 572, 587, 601],
        ),
        ("duration", "2'19''"),
        (
            "fermata_measure_numbers",
            [609],
        ),
        ("final_measure_is_fermata", True),
        ("final_measure_number", 609),
        ("first_measure_number", 556),
        ("segment_name", "11"),
        ("segment_number", 11),
        ("start_clock_time", "24'45''"),
        ("stop_clock_time", "27'04''"),
        (
            "time_signatures",
            [
                "6/8",
                "7/8",
                "6/4",
                "3/4",
                "7/8",
                "5/8",
                "4/8",
                "6/8",
                "8/8",
                "8/8",
                "4/8",
                "5/8",
                "8/8",
                "6/8",
                "8/8",
                "7/8",
                "6/8",
                "7/8",
                "8/8",
                "8/8",
                "8/8",
                "3/4",
                "8/8",
                "6/8",
                "7/8",
                "7/8",
                "6/8",
                "5/8",
                "4/8",
                "6/8",
                "7/8",
                "7/8",
                "4/8",
                "5/8",
                "6/8",
                "8/8",
                "8/8",
                "5/8",
                "4/8",
                "8/8",
                "6/8",
                "8/8",
                "8/8",
                "7/8",
                "6/8",
                "8/8",
                "8/8",
                "6/8",
                "7/8",
                "7/8",
                "6/8",
                "4/8",
                "5/8",
                "1/4",
            ],
        ),
    ]
)
