import abjad


metadata = abjad.OrderedDict(
    [
        (
            'alive_during_segment',
            [
                'Score',
                'Global_Context',
                'Global_Skips',
                'Music_Context',
                'String_Quartet_Staff_Group',
                'Violin_I_Music_Staff',
                'Global_Rests',
                'Violin_I_Music_Voice',
                'Violin_I_Rest_Voice',
                'Violin_II_MusicStaff',
                'Violin_II_Music_Voice',
                'Violin_II_Rest_Voice',
                'Viola_Music_Staff',
                'Viola_Music_Voice',
                'Viola_Rest_Voice',
                'Cello_Music_Staff',
                'Cello_Music_Voice',
                'Cello_Rest_Voice',
                ],
            ),
        (
            'bol_measure_numbers',
            [130, 146, 165, 181, 195],
            ),
        ('duration', "3'48''"),
        (
            'fermata_measure_numbers',
            [135, 140, 199, 206],
            ),
        ('final_measure_is_fermata', True),
        ('final_measure_number', 206),
        ('first_measure_number', 130),
        ('phantom', True),
        ('segment_name', 'C'),
        ('segment_number', 3),
        ('start_clock_time', "5'12''"),
        ('stop_clock_time', "9'00''"),
        (
            'time_signatures',
            [
                '3/4',
                '4/4',
                '4/4',
                '3/4',
                '14/16',
                '1/4',
                '4/4',
                '5/4',
                '6/4',
                '6/4',
                '1/4',
                '3/4',
                '4/4',
                '5/4',
                '4/4',
                '3/4',
                '4/4',
                '4/4',
                '4/4',
                '3/4',
                '5/4',
                '6/4',
                '3/4',
                '4/4',
                '4/4',
                '5/4',
                '6/4',
                '3/4',
                '5/12',
                '3/4',
                '4/4',
                '4/4',
                '4/4',
                '10/16',
                '12/16',
                '3/4',
                '4/4',
                '3/4',
                '4/4',
                '3/4',
                '4/4',
                '4/4',
                '4/4',
                '3/4',
                '4/4',
                '3/4',
                '4/4',
                '3/4',
                '4/4',
                '4/4',
                '4/4',
                '3/4',
                '4/4',
                '3/4',
                '4/4',
                '4/4',
                '5/4',
                '6/4',
                '3/4',
                '8/16',
                '12/16',
                '4/4',
                '3/4',
                '4/4',
                '4/4',
                '4/4',
                '3/4',
                '3/4',
                '4/4',
                '1/4',
                '5/4',
                '6/4',
                '6/4',
                '3/4',
                '4/4',
                '5/4',
                '1/4',
                ],
            ),
        ]
    )
