import abjad


metadata = abjad.OrderedDict(
    [
        (
            'alive_during_segment',
            [
                'Score',
                'Global_Context',
                'Global_Skips',
                'Music_Context',
                'String_Quartet_Staff_Group',
                'Violin_I_Music_Staff',
                'Global_Rests',
                'Violin_I_Music_Voice',
                'Violin_I_Rest_Voice',
                'Violin_II_MusicStaff',
                'Violin_II_Music_Voice',
                'Violin_II_Rest_Voice',
                'Viola_Music_Staff',
                'Viola_Music_Voice',
                'Viola_Rest_Voice',
                'Cello_Music_Staff',
                'Cello_Music_Voice',
                'Cello_Rest_Voice',
                ],
            ),
        (
            'bol_measure_numbers',
            [626, 642],
            ),
        ('duration', "2'06''"),
        ('final_measure_number', 657),
        ('first_measure_number', 626),
        ('phantom', True),
        ('segment_name', 'M'),
        ('segment_number', 13),
        ('start_clock_time', "27'08''"),
        ('stop_clock_time', "29'14''"),
        (
            'time_signatures',
            [
                '10/16',
                '12/16',
                '12/16',
                '12/16',
                '8/16',
                '14/16',
                '14/16',
                '16/16',
                '16/16',
                '8/16',
                '12/16',
                '12/16',
                '16/16',
                '14/16',
                '14/16',
                '16/16',
                '12/16',
                '10/16',
                '16/16',
                '16/16',
                '14/16',
                '14/16',
                '10/16',
                '12/16',
                '12/16',
                '8/16',
                '12/16',
                '12/16',
                '10/16',
                '12/16',
                '12/16',
                '8/16',
                ],
            ),
        ]
    )
