import abjad


metadata = abjad.OrderedDict(
    [
        (
            'alive_during_segment',
            [
                'Score',
                'Global_Context',
                'Global_Skips',
                'Music_Context',
                'String_Quartet_Staff_Group',
                'Violin_I_Music_Staff',
                'Global_Rests',
                'Violin_I_Music_Voice',
                'Violin_I_Rest_Voice',
                'Violin_II_MusicStaff',
                'Violin_II_Music_Voice',
                'Violin_II_Rest_Voice',
                'Viola_Music_Staff',
                'Viola_Music_Voice',
                'Viola_Rest_Voice',
                'Cello_Music_Staff',
                'Cello_Music_Voice',
                'Cello_Rest_Voice',
                ],
            ),
        (
            'bol_measure_numbers',
            [840, 853],
            ),
        ('duration', "1'18''"),
        (
            'fermata_measure_numbers',
            [841, 844, 848, 855, 859],
            ),
        ('final_measure_is_fermata', True),
        ('final_measure_number', 859),
        ('first_measure_number', 840),
        ('phantom', True),
        ('segment_name', 'S'),
        ('segment_number', 19),
        ('start_clock_time', "38'15''"),
        ('stop_clock_time', "39'33''"),
        (
            'time_signatures',
            [
                '4/4',
                '1/4',
                '3/4',
                '4/4',
                '1/4',
                '5/4',
                '6/4',
                '6/4',
                '1/4',
                '3/4',
                '4/4',
                '5/4',
                '4/4',
                '3/4',
                '4/4',
                '1/4',
                '4/4',
                '4/4',
                '3/4',
                '1/4',
                ],
            ),
        ]
    )
