import distutils.version
import platform

from .tools import (
    Operation,
    ScoreTemplate,
    StageSpecifier,
    StageToken,
    accelerando,
    bcps,
    breathe,
    cello_cell,
    cello_cell_bcps,
    circle_spanner,
    circles,
    clockticks,
    clouded_pane,
    clouded_pane_spanner,
    continuous_tremolo,
    declamation,
    desynchronization,
    eighths,
    first_order_stages,
    flight,
    flight_spanner,
    grid,
    grid_to_trajectory,
    instruments,
    left_broken_circle_bow_tweak,
    left_broken_tasto_tweak,
    loure_tuplets,
    margin_markup,
    margin_markups,
    measure_initiation,
    metronome_marks,
    multistage_leaf_glissando,
    ntlt_flat_glissandi,
    operations,
    pickets,
    rasp,
    running_quarter_divisions,
    second_order_stages,
    strokes,
    synchronized_circles,
    tailpiece,
    talea_eighths,
    taper,
    time,
    time_signature_series,
    time_signatures,
    to_flight,
    trajectories,
    trajectory_spanner,
    transition_bcps,
    urtext_field,
    urtext_spanner,
    wave,
)

__all__ = [
    "ScoreTemplate",
    "instruments",
    "margin_markups",
    "metronome_marks",
    "time_signature_series",
    "Operation",
    "StageSpecifier",
    "StageToken",
    "accelerando",
    "bcps",
    "breathe",
    "cello_cell",
    "cello_cell_bcps",
    "circle_spanner",
    "circles",
    "clockticks",
    "clouded_pane",
    "clouded_pane_spanner",
    "continuous_tremolo",
    "declamation",
    "desynchronization",
    "eighths",
    "first_order_stages",
    "flight",
    "flight_spanner",
    "grid",
    "grid_to_trajectory",
    "left_broken_circle_bow_tweak",
    "left_broken_tasto_tweak",
    "loure_tuplets",
    "margin_markup",
    "measure_initiation",
    "multistage_leaf_glissando",
    "ntlt_flat_glissandi",
    "operations",
    "pickets",
    "rasp",
    "running_quarter_divisions",
    "second_order_stages",
    "strokes",
    "synchronized_circles",
    "tailpiece",
    "talea_eighths",
    "taper",
    "time",
    "time_signatures",
    "to_flight",
    "trajectories",
    "trajectory_spanner",
    "transition_bcps",
    "urtext_field",
    "urtext_spanner",
    "wave",
]

if not (
    distutils.version.LooseVersion("3.7")
    < distutils.version.LooseVersion(platform.python_version())
):
    raise ImportError("Requires Python 3.7.")
del distutils
del platform
