import abjad


metadata = abjad.OrderedDict(
    [
        (
            'alive_during_segment',
            [
                'Score',
                'Global_Context',
                'Global_Skips',
                'Music_Context',
                'String_Quartet_Staff_Group',
                'Violin_I_Music_Staff',
                'Global_Rests',
                'Violin_I_Music_Voice',
                'Violin_I_Rest_Voice',
                'Violin_II_MusicStaff',
                'Violin_II_Music_Voice',
                'Violin_II_Rest_Voice',
                'Viola_Music_Staff',
                'Viola_Music_Voice',
                'Viola_Rest_Voice',
                'Cello_Music_Staff',
                'Cello_Music_Voice',
                'Cello_Rest_Voice',
                ],
            ),
        (
            'bol_measure_numbers',
            [64, 82, 96, 115],
            ),
        ('duration', "2'46''"),
        (
            'fermata_measure_numbers',
            [91, 94, 99, 102, 106, 110, 112, 126, 129],
            ),
        ('final_measure_is_fermata', True),
        ('final_measure_number', 129),
        ('first_measure_number', 64),
        ('phantom', True),
        ('segment_name', 'B'),
        ('segment_number', 2),
        ('start_clock_time', "2'26''"),
        ('stop_clock_time', "5'12''"),
        (
            'time_signatures',
            [
                '6/8',
                '7/8',
                '7/8',
                '4/8',
                '5/8',
                '6/8',
                '8/8',
                '8/8',
                '5/8',
                '4/8',
                '8/8',
                '6/8',
                '5/12',
                '8/8',
                '5/12',
                '7/8',
                '5/12',
                '6/8',
                '7/8',
                '8/8',
                '8/8',
                '6/8',
                '7/8',
                '7/8',
                '6/8',
                '8/16',
                '4/8',
                '1/4',
                '5/8',
                '6/8',
                '1/4',
                '8/8',
                '8/8',
                '7/8',
                '7/8',
                '1/4',
                '5/8',
                '4/8',
                '1/4',
                '6/8',
                '8/8',
                '12/16',
                '1/4',
                '8/8',
                '10/16',
                '4/8',
                '1/4',
                '16/16',
                '1/4',
                '5/8',
                '8/8',
                '6/8',
                '8/8',
                '7/8',
                '6/8',
                '7/8',
                '8/8',
                '8/8',
                '6/8',
                '7/8',
                '7/8',
                '6/8',
                '1/4',
                '14/16',
                '5/8',
                '1/4',
                ],
            ),
        ]
    )
