import baca


after_time_signatures = 20
after_staff = 30
first_system_y_offset = 20
second_system_y_offset = 180
third_system_y_offset = 340

breaks = baca.breaks (

    baca.page(
        baca.system(
            after_time_signatures,
            after_staff,
            measure=1,
            y_offset=first_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=9,
            y_offset=second_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=17,
            y_offset=third_system_y_offset,
            ),
        number=1,
        ),
    baca.page(
        baca.system(
            after_time_signatures,
            after_staff,
            measure=25,
            y_offset=first_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=33,
            y_offset=second_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=41,
            y_offset=third_system_y_offset,
            ),
        number=2,
        ),
    baca.page(
        baca.system(
            after_time_signatures,
            after_staff,
            measure=49,
            y_offset=first_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=57,
            y_offset=second_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=65,
            y_offset=third_system_y_offset,
            ),
        number=3,
        ),
    baca.page(
        baca.system(
            after_time_signatures,
            after_staff,
            measure=73,
            y_offset=first_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=81,
            y_offset=second_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=89,
            y_offset=third_system_y_offset,
            ),
        number=4,
        ),
    baca.page(
        baca.system(
            after_time_signatures,
            after_staff,
            measure=97,
            y_offset=first_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=105,
            y_offset=second_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=113,
            y_offset=third_system_y_offset,
            ),
        number=5,
        ),
    baca.page(
        baca.system(
            after_time_signatures,
            after_staff,
            measure=121,
            y_offset=first_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=129,
            y_offset=second_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=137,
            y_offset=third_system_y_offset,
            ),
        number=6,
        ),
    baca.page(
        baca.system(
            after_time_signatures,
            after_staff,
            measure=145,
            y_offset=first_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=153,
            y_offset=second_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=161,
            y_offset=third_system_y_offset,
            ),
        number=7,
        ),
    baca.page(
        baca.system(
            after_time_signatures,
            after_staff,
            measure=169,
            y_offset=first_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=177,
            y_offset=second_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=185,
            y_offset=third_system_y_offset,
            ),
        number=8,
        ),
    baca.page(
        baca.system(
            after_time_signatures,
            after_staff,
            measure=193,
            y_offset=first_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=201,
            y_offset=second_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=209,
            y_offset=third_system_y_offset,
            ),
        number=9,
        ),
    baca.page(
        baca.system(
            after_time_signatures,
            after_staff,
            measure=217,
            y_offset=first_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=225,
            y_offset=second_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=233,
            y_offset=third_system_y_offset,
            ),
        number=10,
        ),
    baca.page(
        baca.system(
            after_time_signatures,
            after_staff,
            measure=241,
            y_offset=first_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=249,
            y_offset=second_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=257,
            y_offset=third_system_y_offset,
            ),
        number=11,
        ),
    baca.page(
        baca.system(
            after_time_signatures,
            after_staff,
            measure=265,
            y_offset=first_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=273,
            y_offset=second_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=281,
            y_offset=third_system_y_offset,
            ),
        number=12,
        ),
    baca.page(
        baca.system(
            after_time_signatures,
            after_staff,
            measure=289,
            y_offset=first_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=297,
            y_offset=second_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=305,
            y_offset=third_system_y_offset,
            ),
        number=13,
        ),
    baca.page(
        baca.system(
            after_time_signatures,
            after_staff,
            measure=313,
            y_offset=first_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=321,
            y_offset=second_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=329,
            y_offset=third_system_y_offset,
            ),
        number=14,
        ),
    baca.page(
        baca.system(
            after_time_signatures,
            after_staff,
            measure=337,
            y_offset=first_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=345,
            y_offset=second_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=353,
            y_offset=third_system_y_offset,
            ),
        number=15,
        ),
    baca.page(
        baca.system(
            after_time_signatures,
            after_staff,
            measure=361,
            y_offset=first_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=369,
            y_offset=second_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=377,
            y_offset=third_system_y_offset,
            ),
        number=16,
        ),
    baca.page(
        baca.system(
            after_time_signatures,
            after_staff,
            measure=385,
            y_offset=first_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=393,
            y_offset=second_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=401,
            y_offset=third_system_y_offset,
            ),
        number=17,
        ),
    baca.page(
        baca.system(
            after_time_signatures,
            after_staff,
            measure=409,
            y_offset=first_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=417,
            y_offset=second_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=425,
            y_offset=third_system_y_offset,
            ),
        number=18,
        ),
    baca.page(
        baca.system(
            after_time_signatures,
            after_staff,
            measure=433,
            y_offset=first_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=441,
            y_offset=second_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=449,
            y_offset=third_system_y_offset,
            ),
        number=19,
        ),
    baca.page(
        baca.system(
            after_time_signatures,
            after_staff,
            measure=457,
            y_offset=first_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=465,
            y_offset=second_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=473,
            y_offset=third_system_y_offset,
            ),
        number=20,
        ),
    baca.page(
        baca.system(
            after_time_signatures,
            after_staff,
            measure=481,
            y_offset=first_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=489,
            y_offset=second_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=497,
            y_offset=third_system_y_offset,
            ),
        number=21,
        ),
    baca.page(
        baca.system(
            after_time_signatures,
            after_staff,
            measure=505,
            y_offset=first_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=513,
            y_offset=second_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=521,
            y_offset=third_system_y_offset,
            ),
        number=22,
        ),
    baca.page(
        baca.system(
            after_time_signatures,
            after_staff,
            measure=529,
            y_offset=first_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=537,
            y_offset=second_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=545,
            y_offset=third_system_y_offset,
            ),
        number=23,
        ),
    baca.page(
        baca.system(
            after_time_signatures,
            after_staff,
            measure=553,
            y_offset=first_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=561,
            y_offset=second_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=569,
            y_offset=third_system_y_offset,
            ),
        number=24,
        ),

    )

spacing = baca.scorewide_spacing(
    __file__,
    breaks=breaks,
    fallback_duration=(1, 16),
    )

#spacing.override(108, (1, 48))
#spacing.override((368, 383), (1, 32))
#spacing.override((425, 442), (1, 12))
#spacing.override((830, 841), (1, 12))
#spacing.override((841, 846), (1, 12))
#spacing.override((856, 859), (1, 12))
#spacing.override((864, 871), (1, 12))


textholding_fermata_measures = [
    10, 19, 24, 28, 61, 63, # A
    91, 129, # B
    140, 199, 206, # C
    243, 252, 270, # D
    346, 391, 416, # E
    443, # F
    454, 464, # G
    609, # K
    696, # N
    704, # O
    839, # R
    848, # S
    855, 859, #S
    ]

spacing.override(textholding_fermata_measures, (1, 288), fermata=True)
