import baca


after_time_signatures = 20
after_staff = 30

# 8 pt:
first_system_y_offset = 12.5
second_system_y_offset = 150
third_system_y_offset = 287.5

breaks = baca.breaks (

    baca.page(
        baca.system(
            after_time_signatures,
            after_staff - 4,
            measure=1,
            y_offset=80,
            ),
        baca.system(
            after_time_signatures,
            after_staff - 4,
            measure=9,
            y_offset=195,
            ),
        baca.system(
            after_time_signatures,
            after_staff - 4,
            measure=18,
            y_offset=310,
            ),
        number=1,
        ),
    baca.page(
        baca.system(
            after_time_signatures,
            after_staff,
            measure=23,
            y_offset=first_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=29,
            y_offset=second_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=41,
            y_offset=third_system_y_offset,
            ),
        number=2,
        ),
    baca.page(
        baca.system(
            after_time_signatures,
            after_staff,
            measure=49,
            y_offset=first_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=60,
            y_offset=second_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=64,
            y_offset=third_system_y_offset,
            ),
        number=3,
        ),
    baca.page(
        baca.system(
            after_time_signatures,
            after_staff,
            measure=73,
            y_offset=first_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=81,
            y_offset=second_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=89,
            y_offset=third_system_y_offset,
            ),
        number=4,
        ),
    baca.page(
        baca.system(
            after_time_signatures,
            after_staff,
            measure=97,
            y_offset=first_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=105,
            y_offset=second_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=113,
            y_offset=third_system_y_offset,
            ),
        number=5,
        ),
    baca.page(
        baca.system(
            after_time_signatures,
            after_staff,
            measure=121,
            y_offset=first_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=130,
            y_offset=second_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=136,
            y_offset=third_system_y_offset,
            ),
        number=6,
        ),
    baca.page(
        baca.system(
            after_time_signatures,
            after_staff,
            measure=145,
            y_offset=first_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=153,
            y_offset=second_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=161,
            y_offset=third_system_y_offset,
            ),
        number=7,
        ),
    baca.page(
        baca.system(
            after_time_signatures,
            after_staff,
            measure=169,
            y_offset=first_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=177,
            y_offset=second_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=185,
            y_offset=third_system_y_offset,
            ),
        number=8,
        ),
    baca.page(
        baca.system(
            after_time_signatures,
            after_staff,
            measure=193,
            y_offset=first_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=200,
            y_offset=second_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=207,
            y_offset=third_system_y_offset,
            ),
        number=9,
        ),
    baca.page(
        baca.system(
            after_time_signatures,
            after_staff,
            measure=217,
            y_offset=first_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=225,
            y_offset=second_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=233,
            y_offset=third_system_y_offset,
            ),
        number=10,
        ),
    baca.page(
        baca.system(
            after_time_signatures,
            after_staff,
            measure=241,
            y_offset=first_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=249,
            y_offset=second_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=257,
            y_offset=third_system_y_offset,
            ),
        number=11,
        ),
    baca.page(
        baca.system(
            after_time_signatures,
            after_staff,
            measure=265,
            y_offset=first_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=273,
            y_offset=second_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=281,
            y_offset=third_system_y_offset,
            ),
        number=12,
        ),
    baca.page(
        baca.system(
            after_time_signatures,
            after_staff,
            measure=289,
            y_offset=first_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=297,
            y_offset=second_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=305,
            y_offset=third_system_y_offset,
            ),
        number=13,
        ),
    baca.page(
        baca.system(
            after_time_signatures,
            after_staff,
            measure=313,
            y_offset=first_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=321,
            y_offset=second_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=329,
            y_offset=third_system_y_offset,
            ),
        number=14,
        ),
    baca.page(
        baca.system(
            after_time_signatures,
            after_staff,
            measure=337,
            y_offset=first_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=345,
            y_offset=second_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=352,
            y_offset=third_system_y_offset,
            ),
        number=15,
        ),
    baca.page(
        baca.system(
            after_time_signatures,
            after_staff,
            measure=361,
            y_offset=first_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=369,
            y_offset=second_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=377,
            y_offset=third_system_y_offset,
            ),
        number=16,
        ),
    baca.page(
        baca.system(
            after_time_signatures,
            after_staff,
            measure=385,
            y_offset=first_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=393,
            y_offset=second_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=401,
            y_offset=third_system_y_offset,
            ),
        number=17,
        ),
    baca.page(
        baca.system(
            after_time_signatures,
            after_staff,
            measure=409,
            y_offset=first_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=418,
            y_offset=second_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=425,
            y_offset=third_system_y_offset,
            ),
        number=18,
        ),
    baca.page(
        baca.system(
            after_time_signatures,
            after_staff,
            measure=433,
            y_offset=first_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=441,
            y_offset=second_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=447,
            y_offset=third_system_y_offset,
            ),
        number=19,
        ),
    baca.page(
        baca.system(
            after_time_signatures,
            after_staff,
            measure=457,
            y_offset=first_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=465,
            y_offset=second_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=473,
            y_offset=third_system_y_offset,
            ),
        number=20,
        ),
    baca.page(
        baca.system(
            after_time_signatures,
            after_staff,
            measure=481,
            y_offset=first_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=489,
            y_offset=second_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=497,
            y_offset=third_system_y_offset,
            ),
        number=21,
        ),
    baca.page(
        baca.system(
            after_time_signatures,
            after_staff,
            measure=505,
            y_offset=first_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=513,
            y_offset=second_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=521,
            y_offset=third_system_y_offset,
            ),
        number=22,
        ),
    baca.page(
        baca.system(
            after_time_signatures,
            after_staff,
            measure=529,
            y_offset=first_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=537,
            y_offset=second_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=545,
            y_offset=third_system_y_offset,
            ),
        number=23,
        ),
    baca.page(
        baca.system(
            after_time_signatures,
            after_staff,
            measure=553,
            y_offset=first_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=561,
            y_offset=second_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=569,
            y_offset=third_system_y_offset,
            ),
        number=24,
        ),
    baca.page(
        baca.system(
            after_time_signatures,
            after_staff,
            measure=577,
            y_offset=first_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=585,
            y_offset=second_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=593,
            y_offset=third_system_y_offset,
            ),
        number=25,
        ),
    baca.page(
        baca.system(
            after_time_signatures,
            after_staff,
            measure=601,
            y_offset=first_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=609,
            y_offset=second_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=617,
            y_offset=third_system_y_offset,
            ),
        number=26,
        ),
    baca.page(
        baca.system(
            after_time_signatures,
            after_staff,
            measure=625,
            y_offset=first_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=633,
            y_offset=second_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=641,
            y_offset=third_system_y_offset,
            ),
        number=27,
        ),
    baca.page(
        baca.system(
            after_time_signatures,
            after_staff,
            measure=649,
            y_offset=first_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=657,
            y_offset=second_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=665,
            y_offset=third_system_y_offset,
            ),
        number=28,
        ),
    baca.page(
        baca.system(
            after_time_signatures,
            after_staff,
            measure=673,
            y_offset=first_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=681,
            y_offset=second_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=689,
            y_offset=third_system_y_offset,
            ),
        number=29,
        ),
    baca.page(
        baca.system(
            after_time_signatures,
            after_staff,
            measure=697,
            y_offset=first_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=705,
            y_offset=second_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=713,
            y_offset=third_system_y_offset,
            ),
        number=30,
        ),
    baca.page(
        baca.system(
            after_time_signatures,
            after_staff,
            measure=721,
            y_offset=first_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=729,
            y_offset=second_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=737,
            y_offset=third_system_y_offset,
            ),
        number=31,
        ),
    baca.page(
        baca.system(
            after_time_signatures,
            after_staff,
            measure=745,
            y_offset=first_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=753,
            y_offset=second_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=761,
            y_offset=third_system_y_offset,
            ),
        number=32,
        ),
    baca.page(
        baca.system(
            after_time_signatures,
            after_staff,
            measure=769,
            y_offset=first_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=777,
            y_offset=second_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=785,
            y_offset=third_system_y_offset,
            ),
        number=33,
        ),
    baca.page(
        baca.system(
            after_time_signatures,
            after_staff,
            measure=793,
            y_offset=first_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=801,
            y_offset=second_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=809,
            y_offset=third_system_y_offset,
            ),
        number=34,
        ),
    baca.page(
        baca.system(
            after_time_signatures,
            after_staff,
            measure=817,
            y_offset=first_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=825,
            y_offset=second_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=833,
            y_offset=third_system_y_offset,
            ),
        number=35,
        ),
    baca.page(
        baca.system(
            after_time_signatures,
            after_staff,
            measure=841,
            y_offset=first_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=849,
            y_offset=second_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure=857,
            y_offset=third_system_y_offset,
            ),
        number=36,
        ),

    )

spacing = baca.scorewide_spacing(
    __file__,
    breaks=breaks,
    fallback_duration=(1, 20),
    )

#spacing.override(108, (1, 48))
#spacing.override((368, 383), (1, 32))
#spacing.override((425, 442), (1, 12))
#spacing.override((830, 841), (1, 12))
#spacing.override((841, 846), (1, 12))
#spacing.override((856, 859), (1, 12))
#spacing.override((864, 871), (1, 12))

# OVERRIDES
spacing.override((12, 16), (1, 16))
spacing.override([18, 20, 22], (1, 40))
spacing.override(25, (1, 40))
spacing.override(29, (1, 40))
spacing.override(60, (1, 40))
spacing.override(89, (1, 40))
spacing.override(253, (1, 40))
spacing.override(261, (1, 40))

textholding_fermata_measures = [
    10, 19, 24, 28, 61, 63, # A
    91, 129, # B
    140, 199, 206, # C
    243, 252, 270, # D
    346, 391, 416, # E
    443, # F
    454, 464, # G
    609, # K
    696, # N
    704, # O
    839, # R
    848, # S
    855, 859, #S
    ]

spacing.override(textholding_fermata_measures, (1, 288), fermata=True)

'''
last_system_start = -7
last_complete_page = 0
measures_per_system = 8
systems_per_page = 3
total_measures = 859
page_count = total_measures / float(systems_per_page * measures_per_system)
page_count = math.ceil(page_count)
mm = baca.sequence(
    [_ * measures_per_system + last_system_start
    for _ in range(1, systems_per_page * page_count + 1)]
    )
tuples = mm.partition_by_counts([systems_per_page], cyclic=True)
string = """    baca.page(
        baca.system(
            after_time_signatures,
            after_staff,
            measure={},
            y_offset=first_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure={},
            y_offset=second_system_y_offset,
            ),
        baca.system(
            after_time_signatures,
            after_staff,
            measure={},
            y_offset=third_system_y_offset,
            ),
        number={},
        ),"""
for i, tuple_ in enumerate(tuples):
    page_number = i + last_complete_page + 1
    first, second, third = tuple_
    print(string.format(first, second, third, page_number))
print()
'''
