import abjad


metadata = abjad.OrderedDict(
    [
        (
            'alive_during_segment',
            [
                'Score',
                'Global_Context',
                'Global_Skips',
                'Music_Context',
                'String_Quartet_Staff_Group',
                'Violin_I_Music_Staff',
                'Global_Rests',
                'Violin_I_Music_Voice',
                'Violin_I_Rest_Voice',
                'Violin_II_MusicStaff',
                'Violin_II_Music_Voice',
                'Violin_II_Rest_Voice',
                'Viola_Music_Staff',
                'Viola_Music_Voice',
                'Viola_Rest_Voice',
                'Cello_Music_Staff',
                'Cello_Music_Voice',
                'Cello_Rest_Voice',
                ],
            ),
        (
            'bol_measure_numbers',
            [447, 457],
            ),
        ('duration', "0'54''"),
        (
            'fermata_measure_numbers',
            [448, 450, 454, 456, 461, 464, 471],
            ),
        ('final_measure_is_fermata', True),
        ('final_measure_number', 471),
        ('first_measure_number', 447),
        ('phantom', True),
        ('segment_name', 'G'),
        ('segment_number', 7),
        ('start_clock_time', "18'22''"),
        ('stop_clock_time', "19'16''"),
        (
            'time_signatures',
            [
                '14/16',
                '1/4',
                '14/16',
                '1/4',
                '8/16',
                '12/16',
                '16/16',
                '1/4',
                '16/16',
                '1/4',
                '10/16',
                '3/4',
                '5/12',
                '12/16',
                '1/4',
                '12/16',
                '8/16',
                '1/4',
                '14/16',
                '12/16',
                '10/16',
                '12/16',
                '8/16',
                '12/16',
                '1/4',
                ],
            ),
        ]
    )
