import abjad


metadata = abjad.OrderedDict(
    [
        (
            'bol_measure_numbers',
            [658, 672, 688],
            ),
        ('duration', "2'59''"),
        (
            'fermata_measure_numbers',
            [693, 696],
            ),
        ('final_measure_is_fermata', True),
        ('final_measure_number', 696),
        ('first_measure_number', 658),
        ('phantom', True),
        ('segment_name', 'N'),
        ('segment_number', 14),
        ('start_clock_time', "30'33''"),
        ('stop_clock_time', "33'32''"),
        (
            'time_signatures',
            [
                '4/8',
                '5/8',
                '8/8',
                '6/8',
                '8/8',
                '7/8',
                '6/8',
                '7/8',
                '8/8',
                '8/8',
                '6/4',
                '3/4',
                '6/8',
                '7/8',
                '7/8',
                '6/8',
                '5/8',
                '4/8',
                '6/8',
                '7/8',
                '7/8',
                '4/8',
                '5/8',
                '6/8',
                '8/8',
                '8/8',
                '5/8',
                '4/8',
                '7/8',
                '8/8',
                '6/8',
                '8/8',
                '7/8',
                '6/8',
                '7/8',
                '1/4',
                '8/8',
                '8/8',
                '1/4',
                ],
            ),
        ]
    )
